### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by BosterJowls** [DakotaPride/Boleatte#2]
good day,

Wanted to play with your mod but got this crash on start-up.

https://pastebin.com/bCWjhSZZ

**Comment by DakotaPride** [comment]
Do you have the latest.log file as well? Sometimes it gives more information than the crash report and could help in fixing the issue.

**Comment by BosterJowls** [comment]
I'll try running it again and get a log file

**Comment by BosterJowls** [comment]
https://pastebin.com/HHQVqtda

Here you go.

**Comment by DakotaPride** [comment]
Did you make sure to add back boleatte for the log? (it doesn't seem to be listed in the mods)

**Comment by BosterJowls** [comment]
I did, that's the last log in there

The launcher won't even progress to the game screen, it just reopens the launcher with a crash notification, I'll try it again.

**Comment by DakotaPride** [comment]
It could potentially be a compatibility error then, if you're using a modpack, please let me know and I can try figuring it out from there.

**Comment by BosterJowls** [comment]
https://pastebin.com/7TVS2v9j

Here's another one with boleatte listed.

**Comment by DakotaPride** [comment]
If this isn't a public modpack/is your own custom modpack, are you aware if any of these mods change damage somehow (as boleatte is currently incompatible with such mods)? In the next version of Boleatte, this hopefully won't be an issue anymore if this is the case.

**Comment by BosterJowls** [comment]
The only mod I can think of that can change damage is PlayerEX, i'll try removing that and try again

**Comment by DakotaPride** [comment]
Looking through the code of PlayerEX, it is likely to be a cause, as it modifies the same variable I modify (making it incompatible). If that still doesn't work, let me know and I'll see what else I can do.

**Comment by BosterJowls** [comment]
I removed playerEx and it's still crashing, gonna look through the pages of all the mods I have to see what else changes damages.

**Comment by BosterJowls** [comment]
Just had another episode, this time I only had a couple of mods and when I added Appleskin the game crashed

**Comment by DakotaPride** [comment]
What happens if you remove Boleatte and then run the game with just those couple of mods and Appleskin?

**Comment by BosterJowls** [comment]
I initially tried adding just UI mods and Biome mods (Biome Makeover, The Graveyard, BYG, Better End/Nether with Boleatte and it ran just fine, i even explored the new dimension, I appleskin and it crashed..

**Comment by DakotaPride** [comment]
I'm not entirely sure what the issue is. After taking a look through Appleskin, I thought that it might be that they use different versions of Fabric API. But, after testing it with 0.62.0 on Fabric Loader 1.14.9 (which is what Boleatte is designed to run on, though should work with other API and Loader versions), it seemed to work just fine with just Fabric API, Boleatte and Appleskin installed. Appleskin might be incompatible with another mod from your list, which could also be causing an issue with Boleatte. Did you happen to see what biome the game had crashed in (as it could be a generation bug unrelated to Appleskin)
